spring:
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.207.243:8848
    alicloud:
      access-key: LTAI5tSaSkqBZzuoVc5CgEdq
      secret-key: znqZiwVsWr9JFBJGxP8CX7PXJn8KOz
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: wu-mall
      sms:
        accessKeyId: LTAI5t8ZKqV6hfCuMh6dp3CW
        accessKeySecret: HJ90WSBV21n9h8SSIeeZdruB7MLoUw

  application:
    name: mall-third-party

server:
  port: 30000