spring:
  cloud:
    nacos:
      server-addr: 81.70.207.243:8848
  application:
    name: mall-search
  thymeleaf:
    cache: false
  session:
    store-type: redis

  redis:
    host: 192.168.136.134
    port: 6379



server:
  port: 12000