spring:
  session:
    store-type: redis
  rabbitmq:
    host: 81.70.207.243
    username: root
    password: Aa1076766987
    port: 5672
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.136.134:3306/mall_oms
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      server-addr: 81.70.207.243:8848
  application:
    name: mall-order
  thymeleaf:
    cache: false
  redis:
    host: 192.168.136.134
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 9000

seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 81.70.207.243:8848
      namespace: ""
      group: DEFAULT_GROUP
      application: seata-tc-server # tc服务在nacos中的服务名称
      cluster: SH
  tx-service-group: seata-demo # 事务组，根据这个获取tc服务的cluster名称
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      seata-demo: SH

mall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10
